### PR TITLE
Development Tooling (Rollup + BrowserSync)

### PR DESCRIPTION
**Pull request by lukeed**
Using Rollup, there is (currently) no way to both recompile changes _and_ reload the current server. Forget about HMR! The Rollup dev process needs a third party to breach the gap & coordinate tasks.

This PR brings back the `webpack-dev-server` utility/behavior while still using Rollup.

> **Note:** This does not alter the bundle's contents or size in any way.

**Changes:**

* Replaced `http-server` with `browser-sync`
* Renamed & relocatd `todomvc-*` static assets.
* Installed Fly for lightweight task watcher & manager
* (Greatly) Simplified all `npm scripts`
* Removed all unused dependencies (Webpack & co)

---

I could have used [`fly-uglify`](https://github.com/flyjs/fly-uglify) and re-applied the UglifyJS2 config using its JS API, but the previous CLI string was already done & straightforward, so I just passed it thru `fly-shell` instead.

### CODE REVIEW

**Comment by lukeed** [comment]
Unless `surge` or `gh-pages` requires the `http-server` because it's simple / static?

**Comment by developit** [comment]
`surge` and `gh-pages` just use the contents of `build`, I was just using `http-server` to test. This still outputs to `build/` for production builds right (`npm run build`)?

**Comment by lukeed** [comment]
That's what I thought. Yup!

**Comment by lukeed** [comment]
@developit This is your call (obviously 😜). Won't care if you trash it, but if you're waiting for me to merge it, I can't.

**Comment by developit** [comment]
Going to check it out locally so I can get acquainted with the dev workflow and check a couple things (sourcemaps etc)

**Comment by developit** [comment]
(sorry for taking an eternity on this, toiling over 7.2 release and some other stuff!)

**Comment by lukeed** [comment]
Cool! No matter to me; can go either way.

**Comment by lukeed** [comment]
Wow this is old 😂

**Pull request closed without merging**
