### PR TITLE
Local server to serve .js and .css from build/

### PR DESCRIPTION
**Pull request by ivanistheone**
Related to #4

### CODE REVIEW

**Comment by developit** [comment]
Looks good! Ignore the build error, that's me sucking at bash.

**Comment by developit** [comment]
Ooh a fix for the other issue for free? You're the best!

**Comment by developit** [comment]
I this its because this isnt doing shell expansion. ncp or copyfiles might work

**Comment by ivanistheone** [comment]
I think i've reached the limit of my understaning of npm so I'm abandoning Travis quest

Let me know if the attempts at fixing were helpful, else I can rebase and drop them fro this PR

**Comment by developit** [comment]
Rebasing might be good, I'm going to see if switching to copyfiles helps. Don't worry about the build, we know your change works :)

**Comment by ivanistheone** [comment]
Ok done; thx for making this project. Using it to start learning.

**Comment by developit** [comment]
Awesome! This example was originally a fork of the React version so you get to learn two things at once :)

**Pull request merged**
