### PR TITLE
Fix Rollup tooling

### PR DESCRIPTION
**Pull request by lukeed**
Seems like you were relying on global installations. This ensures everything is installed locally so that one can grab & go.

### CODE REVIEW

**Comment by lukeed** [comment]
Bonus: Fix Travis build

**Comment by developit** [comment]
Did adding external helpers change the build output size at all?

**Comment by lukeed** [comment]
Rollup is really annoying if it doesn't have it (or its `babel-preset-es2015-rollup`). I'm not sure if it _actually_ reduced size in this case, but it's supposed to. Its purpose is to prevent duplicate helpers, thus helping to shake the tree.

```
The 'classCallCheck' Babel helper is used more than once in your code. It's strongly recommended that you use the "external-helpers" plugin or the "es2015-rollup" preset. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
The 'inherits' Babel helper is used more than once in your code. It's strongly recommended that you use the "external-helpers" plugin or the "es2015-rollup" preset. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
The 'possibleConstructorReturn' Babel helper is used more than once in your code. It's strongly recommended that you use the "external-helpers" plugin or the "es2015-rollup" preset. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```

**Comment by lukeed** [comment]
@developit Re-tested. Yes!

|      | before    | after     |
|------|-----------|-----------|
| min  | `16.4 kb` | `15.0 kb` |
| gzip | `6043 b`  | `5927 b`  |

Once this gets in & solidifies the Rollup build (for future reference?) I'll get started on my Splittable changes.

**Comment by developit** [comment]
Sweet!
I might take a stab at making the actual app code smaller, too. It's a port of the React todomvc, but there's a fair bit of strange stuff that doesn't add much value but does add size (the Model, etc).  I'll do that in a branch though.

**Comment by developit** [comment]
Added you as a collab :)

**Comment by lukeed** [comment]
Thanks :) 

Should I purge the Webpack remnants with this Splittable PR, or one after?

**Comment by developit** [comment]
I still use it for `webpack-dev-server`, so maybe leave it in? Though it gets cluttered..

**Comment by lukeed** [comment]
Yeah. There are alternatives. I'll just make a 2nd PR for that & you can decide at the time. 👍

**Comment by developit** [comment]
Sweet :)
I was thinking about setting up browsersync + rollup or something, but I've never done it. This repo would probably make a good test though, since it's pretty small and it doesn't take very long to do a full build.

**Comment by lukeed** [comment]
Yeah, BrowserSync is always my go-to. The only issue is that `rollup-watch` doesn't terminate; neither does BSync's `watch`.

AFAIK, bare CLI tools alone won't let us get what we're after. Do you mind if I setup a minimal [Fly](https://github.com/flyjs/fly) instance? It's a lightweight alternative to Gulp & nearly 3x faster. 

> Disclaimer: I also maintain it :)

**Comment by developit** [comment]
I don't mind, whatever works!

**Pull request merged**
